### ISSUE TITLE
Python kernel dies at the last cell in MinDE System with Mesoscopic Simulator.ipynb

### ISSUE THREAD

**Issue by kozo2** [ecell/ecell4#104]
### How to reproduce
```
docker pull ecell/ecell4
docker run -dp 443:8888 ecell/ecell4
```
* open 192.168.99.100:443/notebooks/Examples/MinDE%20System%20with%20Mesoscopic%20Simulator.ipynb
or localhost:443/notebooks/Examples/MinDE%20System%20with%20Mesoscopic%20Simulator.ipynb

* run all

**Comment by kaizu** [comment]
This crash is caused due to the following line:
https://github.com/ecell/ecell4/blob/master/ecell4/core/SubvolumeSpace.cpp#L78
