### ISSUE TITLE
Windows 64bit whl support

### ISSUE THREAD

**Issue by kozo2** [ecell/ecell4#120]
- [x] add platform to appveyor.yml

**Comment by kaizu** [comment]
FYI: https://github.com/ogrisel/python-appveyor-demo

**Comment by kaizu** [comment]
https://www.appveyor.com/docs/installed-software/#python
https://pypi.python.org/pypi/Cython/0.24.1#downloads

**Comment by kaizu** [comment]
The compilation failed with the following error:

```
c:\program files (x86)\hdf_group\hdf5\1.8.16\include\H5public.h(152): error C2371: 'ssize_t': redefinition; different basic types
c:\python35-x64\include\pyconfig.h(193): note: see declaration of 'ssize_t'
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2
```

**Comment by kaizu** [comment]
I just gave up to build Python27-x64 on Appveyor once.

https://github.com/conda/conda-build/issues/1327
