### ISSUE TITLE
Python major version switching option for install.sh

### ISSUE THREAD

**Issue by kozo2** [ecell/ecell4#13]

**Comment by kozo2** [comment]
- [ ] selecting option `py2` or `py3`
- [ ] default option `py2`

**Comment by kaizu** [comment]
Extended ``install.sh`` to accept long options specifying Python major version. As a default, Python 2 is selected. ``py2`` and ``py3`` options work in the same way as before.

Additionally, ``--without-python2``, ``--with-python3``, and ``--with-no-python`` options are available.

```sh
$ ./install.sh  # Install Python 2 library. Equivalent to ./install.sh py2
$ ./install.sh --with-python3  # Install both Python 2 and 3 libraries
$ ./install.sh --without-python2 --with-python3  # Equivalent to ./install.sh py3
$ ./install.sh --with-no-python  # No python library will be installed
```

Full description of ``install.sh`` is as follows:

```
Usage: ./install.sh [--without-python2] [--with-python3] [--with-no-python] [--with-no-test] [--with-vtk] [--with-hdf5] [--prefix=PREFIX] [-h] [--help] [py2|py3]
```
