### ISSUE TITLE
Fail to build out-of-source

### ISSUE THREAD

**Issue by 0ncorhynchus** [ecell/ecell4#135]
Scanning dependencies of target ecell4-core
[  1%] Building CXX object ecell4/core/CMakeFiles/ecell4-core.dir/CompartmentSpace.cpp.o
In file included from /home/kato/wrk/ecell4/ecell4/core/CompartmentSpace.cpp:5:
/home/kato/wrk/ecell4/ecell4/core/functions.hpp:7:10: fatal error: 'config.h' file not found
# include "config.h"

```
     ^
```

1 error generated.
make[2]: **\* [ecell4/core/CMakeFiles/ecell4-core.dir/build.make:63: ecell4/core/CMakeFiles/ecell4-core.dir/CompartmentSpace.cpp.o] Error 1
make[1]: **\* [CMakeFiles/Makefile2:124: ecell4/core/CMakeFiles/ecell4-core.dir/all] Error 2
make: **\* [Makefile:139: all] Error 2

**Comment by kaizu** [comment]
```
~/ecell4$ mkdir build
~/ecell4$ cd build
~/ecell4/build$ cmake ..
~/ecell4/build$ make
```

**Comment by kaizu** [comment]
Now the above processes to build should work. But the following files would be newly generated in the source directory yet:

```
python/lib/ecell.egg-info/
python/lib/ecell4/__init__.py
python/setup.py
```

Move these to the build directory.

**Comment by kaizu** [comment]
`python/setup.py` is now generated in the binary directory, but not in the source. However, I could not found the good way to allow to place `python/lib/ecell4/__init__.py` in the binary. I would make another issue for that, and then close this.
