### ISSUE TITLE
error when importing ecell4

### ISSUE THREAD

**Issue by zaleCao** [ecell/ecell4#157]
Hi 

I'm trying to get ecell4 to work on my macOS Sierra with Python 2.7.12 and I go the following error when trying to run:
    
Traceback (most recent call last):
  File "Documents/PhD/ecell/test.py", line 2, in <module>
    from ecell4 import *
  File "/Users/zale/miniconda2/lib/python2.7/site-packages/ecell4/__init__.py", line 1, in <module>
    from ecell4.core import *
ImportError: dlopen(/Users/zale/miniconda2/lib/python2.7/site-packages/ecell4/core.so, 2): Library not loaded: /usr/local/opt/hdf5/lib/libhdf5_cpp.12.dylib
  Referenced from: /Users/zale/miniconda2/lib/python2.7/site-packages/ecell4/core.so
  Reason: image not found

**Comment by kozo2** [comment]
@zaleCao Thank you for reporting this. I confirmed that this error occurs in my Sierra env.
I will upload the new one to PyPI in today.

**Comment by zaleCao** [comment]
@kozo2 Thanks, let me know when its up and I will try again

**Comment by kozo2** [comment]
@zaleCao 
I uploaded the new ecell4 whl (for OSX Python2.7) to PyPI.
Please try
```
/Users/zale/miniconda2/bin/pip install -U ecell
```
and import it again.

**Comment by zaleCao** [comment]
@kozo2 Great, works!
