### ISSUE TITLE
Warnings in cmake phase

### ISSUE THREAD

**Issue by ptrktn** [ecell/ecell4#16]
How to reproduce.

On Debian 8 (Jessie): install build tools and dependencies.
````
root# apt-get install build-essential cmake libhdf5-dev libboost-dev libboost-regex-dev libgsl0-dev
````
Check out sources and invoke cmake
````
user$ git clone git://github.com/ecell/ecell4
user$ cd ecell4/ecell4
user$ cmake .
````
Expected result: cmake finishes cleanly without errors/warnings.

Unexpected result: the following warnings are raised.
````
...
-- Configuring done
CMake Warning (dev) at ecell4/egfrd/CMakeLists.txt:68 (add_dependencies):
  Policy CMP0046 is not set: Error on non-existent dependency in
  add_dependencies.  Run "cmake --help-policy CMP0046" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  The dependency target "BesselTables" of target "ecell4-egfrd" does not
  exist.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
-- Build files have been written to: /home/stable/wrk/ecell4
```

**Comment by kaizu** [comment]
I removed an old line from ecell4/egfrd/CMakeLists.txt to avoid the warning. See https://github.com/ecell/ecell4/commit/cb8631b9d6714c4dd82e23722d8b823bd8684701

FYI, there is no need to move to ecell4/ecell4. Just call "cmake ." in the root directory.
````
user$ git clone git://github.com/ecell/ecell4
user$ cd ecell4
user$ cmake .
````

**Comment by ptrktn** [comment]
Confirmed, no warnings anymore.

The `cd ecell4/ecell4` is copied in verbatim from here:
https://github.com/ecell/ecell4/wiki/Building-ecell4

Perhaps you could amend those instructions?
