### ISSUE TITLE
Error in make phase

### ISSUE THREAD

**Issue by ptrktn** [ecell/ecell4#17]
How to reproduce:
````
user$ git clone git://github.com/ecell/ecell4
user$ cd ecell4/ecell4
user$ cmake .
user$ make
````
Expected result: build finishes cleanly without errors/warnings.

Unexpected result: build terminates with the following error.
````
[ 63%] Building CXX object ecell4/egfrd/CMakeFiles/ecell4-egfrd.dir/SphericalBesselGenerator.cpp.o
/home/stable/wrk/ecell4/ecell4/egfrd/SphericalBesselGenerator.cpp:8:36: fatal error: SphericalBesselTable.hpp: No such file or directory
 #include "SphericalBesselTable.hpp"
                                    ^
compilation terminated.
ecell4/egfrd/CMakeFiles/ecell4-egfrd.dir/build.make:399: recipe for target 'ecell4/egfrd/CMakeFiles/ecell4-egfrd.dir/SphericalBesselGenerator.cpp.o' failed
make[2]: *** [ecell4/egfrd/CMakeFiles/ecell4-egfrd.dir/SphericalBesselGenerator.cpp.o] Error 1
CMakeFiles/Makefile2:556: recipe for target 'ecell4/egfrd/CMakeFiles/ecell4-egfrd.dir/all' failed
make[1]: *** [ecell4/egfrd/CMakeFiles/ecell4-egfrd.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2
````
File `SphericalBesselTable.hpp` is simply missing.

**Comment by kaizu** [comment]
Please use "install.sh".
```
user$ git clone git://github.com/ecell/ecell4
user$ cd ecell4
user$ sudo ./install.sh
```
This will install files into /usr/local. You can change the path by setting PREFIX as:
```
user$ PREFIX=/path/to ./install.sh
```
If you wan to install python packages too, call "install.sh" with "py2" or "py3" like:
```
user$ sudo apt-get install python-setuptools cython
user$ PREFIX=/path/to ./install.sh py2
```

To build ecell4 manually, you have to generate ecell4/egfrd/SphericalBesselTable.hpp and CylindricalBesselTable.hpp before building the other part. This is the reason for the error you reported above.
For the details, see https://github.com/ecell/ecell4/blob/develop/install.sh#L21-L27
The process will be integrated into the CMake step in future release.

**Comment by ptrktn** [comment]
These instructions do not mention one should use the `install.sh` script.
https://github.com/ecell/ecell4/wiki/Building-ecell4

**Comment by kaizu** [comment]
Sorry for making you confused.
We just leave and forget the old information on the Wiki.
README.md is the latest information basically.
Thank you for your report, ptrktn.

**Comment by ptrktn** [comment]
The link to the obsolete instructions in Wiki is gone now, we close this issue.
