### ISSUE TITLE
corrupted double-linked list

### ISSUE THREAD

**Issue by kozo2** [ecell/ecell4#173]
**Backtrace**

https://gist.github.com/kozo2/f80b4e79954a19eb9d8b6fe7f89514b0

**Memory map**

https://gist.github.com/kozo2/73628c9d6bd529dd97547a8160436699

**How to reproduce**

- pip install ecell-4.1.0-cp35-cp35m-manylinux1_x86_64.whl
- Run all https://github.com/ecell/ecell4-notebooks/blob/master/en/tutorials/tutorial3.ipynb

**Comment by kaizu** [comment]
Which version of hdf5 did you use when building the wheel and executing the notebook?

**Comment by kozo2** [comment]
@kaizu hdf5-1.8.14

https://github.com/ecell/ecell4-manylinux/blob/v4.1.0/.travis.yml
is the .travis.yml that was used to create ecell-4.1.0-cp35-cp35m-manylinux1_x86_64.whl

**Comment by kaizu** [comment]
@kozo2 It might be due to a mismatch in the version of hdf5. The wheel built on my environment works well, but the one on pypi returns the error same as above. The version of hdf5 on my environment is `hdf5-1.8.16`. Otherwise, the version `1.8.14` is too old.

**Comment by kozo2** [comment]
tried `hdf5-1.8.16` with `./configure --prefix=/usr/local --disable-shared --enable-static-exec --enable-cxx`
but the `make` failed like https://gist.github.com/kozo2/25eaf571d2cca8f191ebce9cb9497d88
