### ISSUE TITLE
the Species "serial" order is NOT sorted

### ISSUE THREAD

**Issue by kozo2** [ecell/ecell4#23]
It seems species serial order is not sorted now.
This is different from https://github.com/ecell/ecell4#simple-examples

```
>>> from ecell4.core import *
>>> sp = Species("B.A.C")
>>> print(sp.serial())
>>> B.A.C
```

**Comment by kaizu** [comment]
Sorry for forgetting to inform you about changes in Species. Species no longer sorts its UnitSpecies automatically. This is for the efficiency in its instantiation.

It should behave like the following:

```
>>> from ecell4 import *
>>> sp = Species("B.A.C")
>>> print(sp.serial())
B.A.C
>>> print(unique_serial(sp))
A.B.C
```

or

```
>>> print(format_species(sp).serial())
A.B.C
```

Check the latest version in 'develop' branch.
