### ISSUE TITLE
run_simulation fails with "egfrd"

### ISSUE THREAD

**Issue by kozo2** [ecell/ecell4#239]
https://drive.google.com/file/d/1iTRlZaniwwLxgjBAM4q20_rdRhjT-Xe5/view?usp=sharing

will crash with
```
solver='egfrd'
```

When you replace `egfrd` to `gillespie`
This does not crash.

**Comment by kaizu** [comment]
I reproduced this issue. Let me check.

**Comment by kaizu** [comment]
https://github.com/ecell/ecell4/blob/master/ecell4/egfrd/egfrd.hpp#L94-L97

Here is the bug because `matrix_sizes` might be not set even though `rng` is given. I'll fix it soon.

BTW, to avoid this issue now, just stop using `rndseed` or `run_simulation`. Instantiate `EGFRDWorld` by yourself.
