### ISSUE TITLE
more docstring for API doc

### ISSUE THREAD

**Issue by kozo2** [ecell/ecell4#27]
- [x] ecell4.core
- [x] ecell4.ode
- [x] ecell4.gillespie
- [x] ecell4.meso
- [x] ecell4.lattice
- [x] ecell4.bd
- [x] ecell4.egfrd
- [x] ecell4.util
- [x] ecell4.util.decorator
- [x] ecell4.util.viz

**Comment by kaizu** [comment]
Almost done.

**Comment by kaizu** [comment]
I should follow the way of comments in numpy and matplotlib. I will reformat all.

**Comment by kaizu** [comment]
Ok, I reformatted almost all docstrings.

**Comment by kaizu** [comment]
Please refer the following to add a docstring:

https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt

**Comment by kozo2** [comment]
We need to fix
```
ERROR: Unknown directive type "autosummary".
```

**Comment by kaizu** [comment]
Add lines to conf.py as follows:

```python
extensions = [
    'sphinx.ext.autodoc',
    'numpydoc',
    'sphinx.ext.autosummary'
]

numpydoc_show_class_members = False
```

It looks working nicely for me.
See http://stackoverflow.com/questions/20334804/sphinx-autodoc-and-numpydoc also.

**Comment by kaizu** [comment]
Done. Move to Pull Request for ``docstring`` branch.
