### ISSUE TITLE
DLL load failed

### ISSUE THREAD

**Issue by 229668880** [ecell/ecell4#295]
I am using Python3.5 on Windows 10. Get an error:

E:\Anaconda3\lib\site-packages\ecell4\__init__.py in <module>()
----> 1 from ecell4.core import *
      2 from ecell4.util import *
      3 from ecell4 import bd, ode, gillespie, egfrd, spatiocyte, meso
      4
      5 __version__ = '4.1.4'

ImportError: DLL load failed: The specified procedure could not be found.

**Comment by kaizu** [comment]
Thank you for reporting. I reproduced this issue.

**Comment by kaizu** [comment]
https://github.com/cztomczak/cefpython/issues/359

**Comment by 229668880** [comment]
I had installed Visual C++ Redistributable for VS2015, and there is already a msvcp140.dll in my Python 3.5 root directory.
I created an environment of Python 3.6 within anaconda. ecell4 works perfectly.

**Comment by 229668880** [comment]
Both my Python 3.5 and Python 3.6 are  64bit.

**Comment by kaizu** [comment]
`ecell` works on Python 3.5 32bit with the specific version of `hdf5`:

```python
conda install hdf5==1.8.17
```

I'll try 64bit next.

**Comment by kaizu** [comment]
It works on Python 3.5 64bit (Windows 10 64bit).

I'll show what I did below:

```
# Install miniconda Python 3.7 64-bit (https://conda.io/miniconda.html)
# Launch Anaconda Prompt
(base) conda create -n py35 python=3.5 conda
(base) conda activate py35
(py35) conda install hdf5=1.8.17
(py35) pip install ecell
(py35) python
Python 3.5.6 |Anaconda, Inc.| (default, Aug 26 2018, 16:05:27) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import ecell4
```

See also: https://github.com/ecell/ecell4/blob/master/INSTALL.md

**Comment by 229668880** [comment]
Thanks
