### ISSUE TITLE
from ecell4.extra.unit import getUnitRegistry  doesn't work

### ISSUE THREAD

**Issue by 229668880** [ecell/ecell4#296]
My platform: python3.6, windows 10.  I have installed pint module. Got error when run: from ecell4.extra.unit import getUnitRegistry
Error: ModuleNotFoundError: No module named 'ecell4.extra.unit'

Is it my personal problem? or the version of ecell4?
Thanks

**Comment by kaizu** [comment]
Hi. The `unit` feature is NOT available in the current release (`v4.1.4`). It comes soon with the next release.

When you want to try it, you need to install the latest build (`master`). The wheel package for Python 3.6 Win 64bit is available below:

https://ci.appveyor.com/project/kaizu/ecell4/build/1.0.1189/job/x8iro12qcj3uhd76/artifacts

However, please be reminded that the version might be unstable yet.

**Comment by 229668880** [comment]
Tons of thanks
