### ISSUE TITLE
How to define a second order constant

### ISSUE THREAD

**Issue by 229668880** [ecell/ecell4#297]
We often do this:
with reaction_rule():
     A+B>C|0.03
Here, 0.03 is the constant for first order chemical reaction. 

How to set the constant for second chemical reaction? As we know, the constant changes with the concentration of A and B.  Ask this question because I am trying to use ECell for pharmacokinetics and Toxicokinetics.

**Comment by kaizu** [comment]
By the way, a slack channel (https://ecell-project.herokuapp.com/) is open for the question too.

**Comment by 229668880** [comment]
Thank you so much.
