### ISSUE TITLE
3D plot with mplot3d toolkit

### ISSUE THREAD

**Issue by kozo2** [ecell/ecell4#38]
Currently we use [elegans](https://github.com/domitry/elegans) for the particle visualization.
It may be better to add matplotlib mplot3d toolkit to **plot_world** backend

**Comment by kaizu** [comment]
https://stanford.edu/~mwaskom/software/seaborn/tutorial/color_palettes.html

**Comment by kaizu** [comment]
Please review. See http://nbviewer.ipython.org/github/ecell/ecell4/blob/mplot3d/ipynb/TestAnimation.ipynb

**Comment by kaizu** [comment]
The changes related to this issue is merged onto `lattice2spatiocyte` branch.
