### ISSUE TITLE
Travis CI

### ISSUE THREAD

**Issue by kozo2** [ecell/ecell4#41]
- [x] adding OS X Build Environment support
- [ ] Python3.5 for linux (we don't support Python3 for homebrew)
- [ ] [container-based infrastructure](http://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade)
- [ ] adding deployment support #44

**Comment by kaizu** [comment]
- [ ] test libraries after installing on ``osx``.

**Comment by kaizu** [comment]
Once closed. For issues remained in the list , make a new issue for each.
