### ISSUE TITLE
Jupyter notebook for metabolic profile visualization with Cytoscape

### ISSUE THREAD

**Issue by kozo2** [ecell/ecell4#43]
This combination is useful not only for metabolic profile but also for expression profile.
The pathway networks to combine the profiles are
- [ ] KEGG
- [ ] escher
- [ ] wikipathways

**Comment by kozo2** [comment]
https://github.com/opencobra/COBRA.papers/blob/master/2019_efmviz/efmviz_rcy3_ecoli.Rmd
could be used for this purpose.

**Comment by kaizu** [comment]
Moved to https://github.com/ecell/ecell4_docs/issues/28
