### ISSUE TITLE
PyPI packaging

### ISSUE THREAD

**Issue by kozo2** [ecell/ecell4#44]
~~If we don't need to use ppa auth system, it's worth to create deb package for ecell4.~~
We will create PyPI package for E-Cell4.

**Comment by kaizu** [comment]
Additional, but optional, information:
http://docs.travis-ci.com/user/deployment/pypi/

**Comment by kozo2** [comment]
- [x] binary packaging (C++) with checkinstall
- [ ] source packaging (Python)
- [ ] source packaging (C++, Python)

**Comment by kozo2** [comment]
```
python setup.py sdist
```
does not include pxi and pxd files (just includes pyx files).

We need to update setup.py

**Comment by kozo2** [comment]
renamed issue title to **PyPI packaging**

**Comment by kozo2** [comment]
https://github.com/ecell/ecell4/commit/01882d33ee4ce0d7aab4cdf3aca76e58e5765c95

**Comment by kozo2** [comment]
new tasklist
- [ ] manylinux wheels
- [ ] sdist

**Comment by kozo2** [comment]
created the manylinux wheel repo for E-Cell4
https://github.com/ecell/ecell4-manylinux

**Comment by kozo2** [comment]
It seems we can NOT upload E-Cell4 whl files to PyPI because of the file-size.
I close this issue once.
