### ISSUE TITLE
can't install ecell4 on Mac

### ISSUE THREAD

**Issue by ortega2247** [ecell/ecell4#53]
Hi I wanted to start using ecell4 but I have been having problems with the installation. I tried to install ecell4 on my Mac that is running the macOS Mojave version 10.14.5. I tried a conda environment with python 3.6 and another one with python 2.7 and I keep getting the same error:

ERROR: Could not find a version that satisfies the requirement ecell4-base (from ecell4) (from versions: none)
ERROR: No matching distribution found for ecell4-base (from ecell4)

Thanks for the help

**Comment by kaizu** [comment]
First, please confirm which version of Python are you using, 64bit or 32bit?
We do NOT support Python2.7 and 32bit versions.

In addition, only Python 3.7 might be supported now on macOS.
If you need to use rather Python 3.6, please ask.

**Comment by ortega2247** [comment]
Oh yes it works on python 3.7 Thanks for the reply!
