### ISSUE TITLE
can't load an sbml file

### ISSUE THREAD

**Issue by ortega2247** [ecell/ecell4#54]
I tried loading the attached sbml file and obtained the following error: 

ImportError: cannot import name 'generate_ratelaw' from 'ecell4.util.decorator'

I looked into the ecell4.util.decorator and it doesn't import or have a generate_ratelaw function. However, the generate_ratelaw is defined in the ecell4.util.model_parser module

[example_ecell4.xml.zip](https://github.com/ecell/ecell4/files/3249532/example_ecell4.xml.zip)

**Comment by kaizu** [comment]
I fixed some mistakes in our code. Thanks!
In addition to `load_sbml`, I also found a bug in `export_sbml`.

Please download the new version of `ports.py` from https://github.com/ecell/ecell4/raw/master/ecell4/util/ports.py, and try the following code again.

https://gist.github.com/kaizu/b477e452001b2ab2b36ce3c801399079

This update would be released soon.

In `ecell4`, `sbml` is not fully supported. Please ask when you have some trouble with it again.

**Comment by ortega2247** [comment]
I just checked the example and the load_sbml and save_sbml functions are working. Thanks for the help!
