### ISSUE TITLE
plot_movie doesn't work

### ISSUE THREAD

**Issue by kaizu** [ecell/ecell4#54]
Test `ipynb/TestMovie.ipynb`.

**Comment by kaizu** [comment]
Firefox fails with ``TypeError: data is undefined elegans.js:3088:14``.

**Comment by kaizu** [comment]
It happens only when new species are synthesized during the simulation.

**Comment by domitry** [comment]
Maybe fixed with the commit:
https://github.com/domitry/elegans/commit/2c5c6738e3f9386805146b38367d75492b284b21

**Comment by domitry** [comment]
I'll try it at the lab.

**Comment by kaizu** [comment]
I tested it. It works fine now. Thx!
