### ISSUE TITLE
Cofirming liscense notes

### ISSUE THREAD

**Issue by kaizu** [ecell/ecell4#69]

**Comment by kaizu** [comment]
I asked shafi. He agreed to remove detailed license header lines from `epdp` files. But, its copyright (especially, authors) should be respected. We should recover the author list, and add them to the files newly developed on ecell4 too.

About the license, GPL v2 is enough now (means that we don't need to update to GPL v3). If anyone have opinion about that, please let me know here.

**Comment by kaizu** [comment]
```cpp
/**
[Module name]

Copyright (c) [year] [fullname]

This software is released under the MIT License.
http://opensource.org/licenses/mit-license.php
*/
```

Or

See http://www.gnu.org/licenses/gpl-howto.html

**Comment by kozo2** [comment]
This Google Sheet is helpful. (written only in Japanese)

https://docs.google.com/spreadsheets/d/1smp9rjunA2DeagL65gy2fqUC-7i-90gQZk2uJ81hE0M/edit#gid=0
