### ISSUE TITLE
sim.run() crashes on develop branch

### ISSUE THREAD

**Issue by kozo2** [ecell/ecell4#73]
```
sim.run(duration, (obs1, obs2))
```
in https://github.com/ecell/ecell4/commit/8090ec18a6308fd6205b3fc2bbed9ff129a46c08 crashes like the following image.

<img width="1186" alt="screenshot 2015-12-17 18 41 07" src="https://cloud.githubusercontent.com/assets/12192/11866337/d157a40e-a4ed-11e5-8b2b-fc185f08ebb9.png">

**Comment by kaizu** [comment]
Is this reproducible on the current develop branch, @kozo2 ?

**Comment by kaizu** [comment]
Display a better error message when HDF5 is not supported.
