### ISSUE TITLE
kernel dies after the fifth tutorial sim.run() in tutorials branch

### ISSUE THREAD

**Issue by kozo2** [ecell/ecell4#74]
<img width="1207" alt="screenshot_2015-12-23_15_20_37" src="https://cloud.githubusercontent.com/assets/12192/11971991/f2d31f56-a988-11e5-84e7-d1f860c451e7.png">

**Comment by kaizu** [comment]
This is because the output directory "data" does not exist. Observer should check the root path before writing.

**Comment by kaizu** [comment]
I added a code to check existence of the root path. Now the code above must raise an error with some message.
But I only tested on Linux.
It can fail on Windows platform though I also added a code specific to the environment.
