### ISSUE TITLE
Better styles for visualization especially for matplotlib

### ISSUE THREAD

**Issue by kaizu** [ecell/ecell4#79]
`seaborn` is not available for `mplot3d` now. Provide a beautiful visualization as `elegans` does.

**Comment by kaizu** [comment]
`viz.plot_world_with_attractive_mpl` use the custom style as follows:

![index](https://cloud.githubusercontent.com/assets/778255/14419029/d13ab9a0-fffd-11e5-9a11-dd209e6a4c47.png)

**Comment by kozo2** [comment]
I confirmed ```viz.plot_world_with_attractive_mpl``` works well in the tutorial ```1. Brief Tour of E-Cell4 Simulations```.
