### ISSUE TITLE
Releasing 4.0.0

### ISSUE THREAD

**Issue by kozo2** [ecell/ecell4#91]
## build and delployment
- [x] setup.py version update
- [x] tagging https://github.com/ecell/ecell4/commit/71741fa759f0c98507d486d2ab7b72f29819947e
- [x] windows whl https://ci.appveyor.com/project/kozo2/ecell4/build/1.0.363
- [x] homebrew url update(to tagged source) https://travis-ci.org/ecell/homebrew-ecell4/builds/104791872
- [x] mac whl https://bintray.com/kozo2/generic/ecell4-wheels/view#files/dist
- [x] docker image update https://hub.docker.com/r/ecell/ecell4/builds/

## test
- [x] docker
- [x] windows wheels
- [x] mac wheels
- [x] mac homebrew

## documents
- [x] release note
- [x] deployment

**Comment by kaizu** [comment]
See https://github.com/ecell/ecell4/releases/tag/4.0.0
