### ISSUE TITLE
Tyson1991 run_simulation never ends with boost 1.60.0

### ISSUE THREAD

**Issue by kozo2** [ecell/ecell4#92]
It seems that ODEint in boost 1.60.0 does NOT work for Tyson1991.ipynb in Examples directory.
I confirmed that it works well with boost 1.56 or earlier.

**Comment by kaizu** [comment]
Some update in boost 1.60.0 seems causing it.
www.boost.org/users/history/version_1_60_0.html

boost 1.57, 58, 59 have almost no update in odeint.

**Comment by kaizu** [comment]
The following is enough to avoid the problem:

```python
# after declaring a simulator
print(sim.absolute_tolerance())  # must return 1e-10
sim.set_absolute_tolerance(1e-6)
# before running simulation
```

It might be reasonable to use the larger default value.

**Comment by kaizu** [comment]
`1e-7` was not acceptable for the absolute tolerance. `1e-6` looks too large for me, but examples in boost document actually uses the value.

http://www.boost.org/doc/libs/1_60_0/libs/numeric/odeint/doc/html/boost_numeric_odeint/tutorial/stiff_systems.html

**Comment by kozo2** [comment]
I put aside boost 1.6.0 support for now.
